"""add message artifacts

Revision ID: 17f3093c12c7
Revises: f90bedc1b312
Create Date: 2026-09-04 00:30:12.707932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f3093c12c7'
down_revision: Union[str, Sequence[str], None] = 'f90bedc1b312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('artifacts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'artifacts')
    # ### end Alembic commands ###
